spring:
  application:
    name: auth-chatting-system

logging:
  level:
    root: info

app:
  security:
    token:
      access-token-expiration: 15m
      refresh-token-expiration: 14d
      access-secret: ${ACCESS_SECRET:}
      refresh-secret: ${REFRESH_SECRET:}
      issuer: practice-auth
      audience: practice-client
      impl: nimbus # 필수 값은 아님. 없으면 nimbus를 Default로 사용함

    user-session:
      ttl: 14d
      max-devices: 5
      expiration-policy: absolute # 없으면 absolute 기본
      concurrent-policy: multi # 없으면 multi 기본

    refresh-cookie:
      refresh-token-expiration: 14d
      secure: false # prod는 항상 true

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/my_auth_system_db?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
