spring:
  application:
    name: my-auth-system

logging:
  level:
    root: info

my-auth-system:
  security:
    token:
      access-token-expiration: 15m
      refresh-token-expiration: 14d
      access-secret: ${ACCESS_SECRET:}
      refresh-secret: ${REFRESH_SECRET:}
      issuer: practice-anything-auth
      audience: practice-anything-client

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/my_auth_system_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/my_auth_system_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
